### ISSUE TITLE
`evilified-state-evilify` not working properly on 28.1

### ISSUE THREAD

**Issue by manuelbb-upb** [dalanicolai/pdf-layer#1]
Hi, thanks for the great package.
After replacing the original layer with your private layer, I noticed that the leader key was not working properly anymore (it scrolled instead of providing me the command menu).
At first I thougt it related to [this issue](https://github.com/syl20bnr/spacemacs/issues/15106).
But then I noticed the following warning:
```pdf-tools/:config: Symbol’s function definition is void: evilified-state-evilify```

So I replaced the definition of `pdf/init-pdf-tools ()` with the code from [the current development version](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Breaders/pdf/packages.el) and now it works as expected again.

**Comment by dalanicolai** [comment]
Thanks for the report. I had updated the definition already a while ago, but now I've found that I forgot to push it to github; so I did that now. Please try again...

**Comment by manuelbb-upb** [comment]
Yes, it's gone now, leader key works out of the box.
